Load In NumPy 

In [2]:
import numpy as np

The Basic Manipulation

In [5]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
b = np.array([[1,2,3,4,9,8,0],[5,6,7,8,7,3,1]])
print(b)

[[1 2 3 4 9 8 0]
 [5 6 7 8 7 3 1]]


In [16]:
#get size
b.size

14

In [17]:
#get dimenision
b.ndim

2

In [18]:
#getting shape
#no of rows and columns
b.shape

(2, 7)

In [19]:
#length of each element of array in byte
b.itemsize

4

In [21]:
#data type
b.dtype


dtype('int32')

In [24]:
! jt -l

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [33]:
! jt -t oceans16

Accesing or changing specific element in a row or column 

In [29]:
c = np.array([[1,2,3,4], [5,6,7,8]])
print(c)


[[1 2 3 4]
 [5 6 7 8]]


In [30]:
#getting specific element
c[0,3]

4

In [31]:
c[0, :]

array([1, 2, 3, 4])

In [34]:
c[:, 2]

array([3, 7])

In [39]:
#3D ARRAY
d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [40]:
d[1,1,1]

11

In [41]:
d[:, 1, 2]

array([ 6, 12])

In [46]:
d[:,1,:]

array([[ 4, 91,  6],
       [10, 11, 12]])

In [47]:
d[:,1,:] = [[0,1,2],[3,4,5]]

In [48]:
print(d)

[[[1 2 3]
  [0 1 2]]

 [[7 8 9]
  [3 4 5]]]


In [45]:
#modyfying the values in teh 3D ARRAY
d[0,1,1] = 91
print(d)

[[[ 1  2  3]
  [ 4 91  6]]

 [[ 7  8  9]
  [10 11 12]]]


INITIALIZE DIFFERENT TYPES OF ARRAY

In [57]:
#ARRAY WITH ZEROES

np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.zeros((2,3,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [58]:
np.ones(3)

array([1., 1., 1.])

In [59]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [65]:
#full method

np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [66]:
#full like
np.full_like(b, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [70]:
#RANDOM DECIMAL NUMBER

np.random.rand(2,4)

array([[0.59273375, 0.87076345, 0.05778862, 0.91542848],
       [0.5029639 , 0.96519059, 0.86816656, 0.91320314]])

In [84]:
#generating random integers values
np.random.randint(1,7, size = (3,3))

array([[6, 2, 2],
       [1, 5, 6],
       [6, 6, 6]])

In [86]:
#IDENTITY MATRIX

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
#repeat matrix
arr = np.array([[1,2,3],[5,6,7]])
n1 = np.repeat(arr, 3, axis = 0)
print(n1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [5 6 7]
 [5 6 7]
 [5 6 7]]


In [93]:
a1 = np.array([[[1,2,3],[4,5,6]],[[1,2,1],[5,6,7]]])
print(a1)

[[[1 2 3]
  [4 5 6]]

 [[1 2 1]
  [5 6 7]]]


In [120]:
c3 = np.ones((5,5))
print(c3)
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [121]:
c3[1:4, 1:4] = z
print(c3)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
l = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
l

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

#### be careful while copying arrays

In [14]:
#copying and changing the value of b also changes the value of A becase here 
# b = a basically points to the same memory location.
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)

#this wont't work

[100   2   3]
[100   2   3]


In [19]:
# this will work

a = np.array([1,2,3])
print(a)
b = a.copy()
b[0] = 100
print(b)

[1 2 3]
[100   2   3]


MATHEMATICS

In [23]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [24]:
a + 2

array([3, 4, 5, 6])

In [25]:
a * 2

array([2, 4, 6, 8])

In [26]:
a / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [27]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [28]:
# implementing some Trigonometric functions
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [29]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [30]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

MATRIX MULTIPLICATION

In [39]:
a = np.full((2,3), 3)
print(a)
b = np.ones((3,2))
print(b)

[[3 3 3]
 [3 3 3]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
np.matmul(a,b)

array([[9., 9.],
       [9., 9.]])

In [44]:
#finding the determinant
a = np.identity(3)
np.linalg.det(a)

1.0

In [52]:
#inverse of matrix
a = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(a)
ainv = np.linalg.inv(a)
ainv

[[1 2 3]
 [4 5 6]
 [6 7 8]]


array([[ 1.7156570e+15, -4.2891425e+15,  2.5734855e+15],
       [-3.4313140e+15,  8.5782850e+15, -5.1469710e+15],
       [ 1.7156570e+15, -4.2891425e+15,  2.5734855e+15]])

In [61]:
a = np.array([[1,2,3],[5,6,7]])
print(a)
b = np.array([[1,2,3],[1,2,3]])
print(b)

c = a +2* b
print(c)

[[1 2 3]
 [5 6 7]]
[[1 2 3]
 [1 2 3]]
[[ 3  6  9]
 [ 7 10 13]]


STATISTICS

In [62]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
print(np.min(a))

print(np.max(a))

1
6


In [75]:
print(np.sum(a, axis = 0))

[5 7 9]


In [76]:
print(np.sum(a, axis = 1))

[ 6 15]


In [80]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

RESHAPING

In [86]:
a = np.array([[1,2,3,4],[4,5,6,8]])
a
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 8]])

In [94]:
#vertical stacking vector
v1 = np.array([1,2,3,4])
print (v1)
v2 = np.array([5,6,7,8])
print(v2)

print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v2]))

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [104]:
s = np.array([[1,2,3,4],[5,6,7,8]])
s.reshape(2,4)
print(s)
for i in s:
    print(i)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[5 6 7 8]


In [113]:
import os
a = np.array([i+j for i in range(3)
             for j in range(3)])
a

array([0, 1, 2, 1, 2, 3, 2, 3, 4])

In [128]:
#creating and loading file in numpy
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x
np.savetxt("test.txt", x)

y = np.loadtxt("test.txt")
y = y.astype('float32')
y


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)